# Generated by Django 5.1.4 on 2025-03-14 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shopkeeper',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.CharField(max_length=50)),
                ('shopname', models.CharField(max_length=50)),
                ('shoptype', models.CharField(max_length=50)),
                ('shopowner', models.ImageField(default='', upload_to='static/')),
                ('shopimage', models.ImageField(default='', upload_to='static/')),
                ('district', models.CharField(max_length=50)),
                ('mandal', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('district', models.CharField(default='Unknown', max_length=50)),
                ('mandal', models.CharField(default='Unknown', max_length=50)),
                ('village', models.CharField(default='Unknown', max_length=50)),
                ('area', models.CharField(default='Unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.FloatField()),
                ('productimageone', models.ImageField(upload_to='static/')),
                ('productimagetwo', models.ImageField(upload_to='static/')),
                ('productinfo', models.TextField()),
                ('shop_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.shopkeeper')),
            ],
        ),
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='static/')),
                ('quantity', models.IntegerField()),
                ('number', models.BigIntegerField()),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.addproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopapp.signup')),
            ],
        ),
    ]
