# Generated by Django 5.1.6 on 2025-03-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='date',
        ),
    ]
