# Generated by Django 5.1.4 on 2026-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='h_no',
            field=models.TextField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='near_by',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
