# Generated by Django 5.1.4 on 2026-02-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_signup_h_no_signup_near_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='near_by',
            field=models.TextField(default='Unknown', max_length=50),
        ),
    ]
