# Generated by Django 5.1.4 on 2026-02-03 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_alter_signup_near_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='otp',
        ),
        migrations.AddField(
            model_name='buy',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buy',
            name='otp_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
