# Generated by Django 5.1.4 on 2026-02-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_remove_buy_is_verified_remove_buy_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buy',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
