# Generated by Django 5.1.4 on 2026-02-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_buy_is_verified_buy_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
