# Generated by Django 5.1.4 on 2026-02-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_signup_is_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='buy',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
