# Generated by Django 5.1.4 on 2026-02-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_remove_signup_is_confirmed_buy_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
