# Generated by Django 6.0.6 on 2026-08-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_buy_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
