# Generated by Django 5.1.4 on 2026-09-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_shopkeeper_latitude_shopkeeper_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signup',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
